### ISSUE TITLE
Slf4jLogShouldBeConstant: Cannot invoke "org.openrewrite.java.tree.J.withPrefix(org.openrewrite.java.tree.Space)" because "parameter" is null

### ISSUE THREAD

**Issue by antonleliuk** [openrewrite/rewrite-logging-frameworks#89] opened 2023-01-15 14:38 UTC
I'm trying to migrate from Log4j to Log4j2 and I got an exception
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.J.withPrefix(org.openrewrite.java.tree.Space)" because "parameter" is null
    at org.openrewrite.java.internal.template.Substitutions.lambda$substitute$0 (Substitutions.java:117)
    at org.openrewrite.internal.PropertyPlaceholderHelper.parseStringValue (PropertyPlaceholderHelper.java:90)
    at org.openrewrite.internal.PropertyPlaceholderHelper.replacePlaceholders (PropertyPlaceholderHelper.java:64)
    at org.openrewrite.java.internal.template.Substitutions.substitute (Substitutions.java:47)
    at org.openrewrite.java.JavaTemplate.withTemplate (JavaTemplate.java:70)
    at org.openrewrite.java.JavaTemplate.withTemplate (JavaTemplate.java:42)
    at org.openrewrite.java.tree.J.withTemplate (J.java:91)
    at org.openrewrite.java.logging.slf4j.Slf4jLogShouldBeConstant$1.visitMethodInvocation (Slf4jLogShouldBeConstant.java:92)
    at org.openrewrite.java.logging.slf4j.Slf4jLogShouldBeConstant$1.visitMethodInvocation (Slf4jLogShouldBeConstant.java:62)

```
Plugin configuration is
```
<plugin>
	<groupId>org.openrewrite.maven</groupId>
	<artifactId>rewrite-maven-plugin</artifactId>
	<version>4.38.2</version>
	<configuration>
		<activeRecipes>
			<recipe>org.openrewrite.java.logging.slf4j.Log4jToSlf4j</recipe>
			<recipe>org.openrewrite.java.logging.log4j.ParameterizedLogging</recipe>
			<recipe>org.openrewrite.java.logging.slf4j.Slf4jBestPractices</recipe>
		</activeRecipes>
		<exclusions>
			<exclusion>.svn/**</exclusion>
			<exclusion>**/*.rtf</exclusion>
			<exclusion>**/*.pdf</exclusion>
			<exclusion>**/*.xls</exclusion>
			<exclusion>**/*.xlsx</exclusion>
			<exclusion>**/*.csv</exclusion>
			<exclusion>**/*.txt</exclusion>
			<exclusion>**/*.yml</exclusion>
			<exclusion>**/*.yaml</exclusion>
		</exclusions>
	</configuration>
	<dependencies>
		<!-- https://mvnrepository.com/artifact/org.openrewrite.recipe/rewrite-migrate-java -->
		<dependency>
			<groupId>org.openrewrite.recipe</groupId>
			<artifactId>rewrite-migrate-java</artifactId>
			<version>1.15.0</version>
			<scope>runtime</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.openrewrite.recipe/rewrite-logging-frameworks -->
		<dependency>
			<groupId>org.openrewrite.recipe</groupId>
			<artifactId>rewrite-logging-frameworks</artifactId>
			<version>1.16.0</version>
		</dependency>
	</dependencies>
</plugin>
```
Is it possible to add more detailed log message to find out the statement in code that causes an error?

**Comment by timtebeek** [comment] 2023-01-16 17:23
hi @antonleliuk Thanks for reporting this! Unfortunately there's not yet a way (that I know of) to find exactly what line is causing issues, although [it's been suggested before](https://github.com/openrewrite/rewrite/issues/2655). I hope we can add such diagnostics fairly quickly, so we can better help you pinpoint the exact cause of the issue, and resolve the suspected bug in the `Slf4jLogShouldBeConstant` recipe that's troubling you here.

**Comment by timtebeek** [comment] 2023-01-17 21:06
@antonleliuk a change was just [merged into openrewrite/rewrite](https://github.com/openrewrite/rewrite/pull/2664) which will allow you to find out which file, class and or method are causing issues with a recipe whenever an unexpected exception occurs. Keep an eye out for the upcoming release!

Once the release has gone through we'd be really interested in the lines that currently cause the recipe to trip up, so we can fix that for you as well. You're welcome to just post those lines here if you can, but even better would be a pull request [with a reproducing test](https://github.com/openrewrite/rewrite-logging-frameworks/blob/main/src/test/java/org/openrewrite/java/logging/log4j/Log4j1ToLog4j2Test.java#L40).

Let me know how you get on; happy to help!

**Comment by timtebeek** [comment] 2023-05-06 21:10
@antonleliuk The recipe has seen extensive changes since you're reported this issue; most recently in https://github.com/openrewrite/rewrite-logging-frameworks/pull/103 .
I'm going to assume the issue has since been fixed, but would really appreciate it if you could verify that [with the latest snapshot version](https://docs.openrewrite.org/reference/snapshot-instructions).

In any case our improved diagnostics should now pinpoint the exact location in your code if there's still an issue, such that you would be able to provide us with an example. Feel free to reopen if needed!

**Closed by timtebeek** 2023-05-06 21:10 UTC
Labels: bug

**Comment by antonleliuk** [comment] 2023-05-21 14:22
I'm sorry it took so long, but we had a major task of transitioning to Hibernate 6, and until we completed it, the project wouldn't compile. I've created a small example to reproduce the error.
```java
public class Profession implements Cloneable {

    private static final Logger log = LoggerFactory.getLogger(Profession.class);

    private String description;

    public Profession clone(double salary) {
        Profession copy = null;
        try {
            copy = (Profession) super.clone();
        } catch (CloneNotSupportedException e) {
            log.error(toString(), e);
        }

        return copy;
    }

    @Override
    public String toString() {
        return description;
    }

}
```
If I change `log.error(toString(), e);` to the `log.error(description, e);` it works well

**Comment by timtebeek** [comment] 2023-05-22 08:04
> I'm sorry it took so long, but we had a major task of transitioning to Hibernate 6, and until we completed it, the project wouldn't compile.

No problem at all! Any Hibernate 6 changes we could capture in recipes such that others can migrate more easily? :)

> I've created a small example to reproduce the error.
> 
> ```java
> package com.sample;
> 
> import org.slf4j.Logger;
> import org.slf4j.LoggerFactory;
> 
> public class Profession implements Cloneable {
> 
>     private static final Logger log = LoggerFactory.getLogger(Profession.class);
> 
>     private String description;
> 
>     public Profession clone(double salary) {
>         Profession copy = null;
>         try {
>             copy = (Profession) super.clone();
>         } catch (CloneNotSupportedException e) {
>             log.error(toString(), e);
>         }
> 
>         return copy;
>     }
> 
>     @Override
>     public String toString() {
>         return description;
>     }
> 
> }
> ```
> 
> If I change `log.error(toString(), e);` to the `log.error(description, e);` it works well. I use the latest versions of dependencies (rewrite-maven-plugin, rewrite-migrate-java, rewrite-logging-frameworks) from the repository.

Thanks for the reproduction sample! I've pinned the issue down using a reduced sample and likely solved it going forward with: https://github.com/openrewrite/rewrite-logging-frameworks/pull/108/files
