### ISSUE TITLE
`StaticImports` incorrectly removes used import, but only on JDK17, not JDK21

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-logging-frameworks#177] opened 2024-08-21 05:21 UTC
Context: https://github.com/JabRef/jabref/blob/f4e87e5ef45bd87c373b17717343a59af7b4e931/rewrite.yml#L208

When using JDK21, everything is fine.

When using JDK17, imports are removed

    set JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.12.7-hotspot   

```
Changes have been made to src\test\java\org\jabref\gui\autocompleter\BibEntrySuggestionProviderTest.java by:
    org.openrewrite.java.testing.junit5.StaticImports
        org.openrewrite.java.UseStaticImport: {methodPattern=org.junit.jupiter.api.Assertions *(..)}
```

```diff
--- a/src/test/java/org/jabref/gui/autocompleter/BibEntrySuggestionProviderTest.java
+++ b/src/test/java/org/jabref/gui/autocompleter/BibEntrySuggestionProviderTest.java
@@ -11,7 +11,6 @@ import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;

 import static org.jabref.gui.autocompleter.AutoCompleterUtil.getRequest;
-import static org.junit.jupiter.api.Assertions.assertEquals;
 import static org.junit.jupiter.api.Assertions.assertThrows;

 class BibEntrySuggestionProviderTest {
diff --git a/src/test/java/org/jabref/gui/autocompleter/PersonNameSuggestionProviderTest.java b/src/test/java/org/jabref/gui/autocompleter/PersonNameSuggestionProviderTest.java
index 980868f730..e9d112ae33 100644
```

This import, however, is necessary.

---

Since [JDK17 is eol in 5 years](https://endoflife.date/oracle-jdk) from now, I wanted to report the issue. If someone stumbles over it.

**Comment by timtebeek** [comment] 2024-08-21 09:56
Very strange that you're seeing differences on those two Java versions. You might want to check the very latest Gradle plugin version, as I see you're using an older version still that does not contain a recent fix to detect missing method types.

- https://github.com/JabRef/jabref/blob/f4e87e5ef45bd87c373b17717343a59af7b4e931/build.gradle#L32
- https://github.com/openrewrite/rewrite-gradle-plugin/releases/tag/v6.20.1
- https://github.com/openrewrite/rewrite/pull/4406

**Comment by subhramit** [comment] 2024-08-21 10:55
> Very strange that you're seeing differences on those two Java versions. You might want to check the very latest Gradle plugin version, as I see you're using an older version still that does not contain a recent fix to detect missing method types.
> 
> * https://github.com/JabRef/jabref/blob/f4e87e5ef45bd87c373b17717343a59af7b4e931/build.gradle#L32
> * https://github.com/openrewrite/rewrite-gradle-plugin/releases/tag/v6.20.1
> * [`NoMissingTypes` does not work if the missing type is a return value of a method and the method has a parameter rewrite#4406](https://github.com/openrewrite/rewrite/pull/4406)

Hi, JabRef developer here.
Issue persists on trying `.\gradlew rewriteRun` with `id 'org.openrewrite.rewrite' version '6.20.1'` in `build.gradle`.

**Comment by timtebeek** [comment] 2024-09-06 17:42
We just merged a fix for a very similar issue, there affecting static imports of variables, not methods:
- https://github.com/openrewrite/rewrite/pull/4450

Figured that might be interesting to call out here as the fix could be similar.

**Comment by timtebeek** [comment] 2024-11-24 21:11
Reading this issue again I think it's logged against the wrong project. With the changes since it's hard to say if this has been solved or not; If you feel there's anything left to do then let's open an issue against rewrite-testing-frameworks with steps to reproduce, as it looks like StaticImports has been permanently enabled there already:
https://github.com/JabRef/jabref/blob/de81430c1472920304c8348207ee2af9ec525822/rewrite.yml#L212

**Closed by timtebeek** 2024-11-24 21:11 UTC
Labels: bug

**Comment by koppor** [comment] 2024-11-25 23:32
Just for reference:

- Fails: `JAVA_HOME=CC:\Program Files\Eclipse Adoptium\jdk-21.0.5.11-hotspot`
- Works: `JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-23.0.1.11-hotspot`

**Comment by subhramit** [comment] 2024-11-30 06:08
I think this is becoming increasingly common:
https://github.com/JabRef/jabref/pull/12246#issuecomment-2508840286
https://github.com/JabRef/jabref/pull/12198/commits/f37793967797f786bd329efd1459668f51791873

**Comment by timtebeek** [comment] 2024-11-30 09:07
Sorry to hear; Are there any missing types perhaps that differ between 21 and 21? Useing the [Find missing types recipe](https://docs.openrewrite.org/recipes/java/search/findmissingtypes), and [the data table it produces](https://docs.moderne.io/user-documentation/data-tables), do you find any missing types in your codebase? If there are any missing types you might want to double-check your dependencies are set up correctly, or whether you're using Lombok, as [Lombok leads to missing types](https://github.com/openrewrite/rewrite/issues/1297).

Any help troubleshooting this would be appreciated, as it's hard for me to find the time with the amount of requests we have coming in.

**Comment by Siedlerchr** [comment] 2024-12-01 17:06
I encountered this issue on 21.0.2 temurin

**Comment by koppor** [comment] 2024-12-01 19:39
> Sorry to hear; Are there any missing types perhaps that differ between 21 and 21? Useing the [Find missing types recipe](https://docs.openrewrite.org/recipes/java/search/findmissingtypes), 

In the Java code exclusively in the JavaDoc commts

```diff
     /**
-     * @implNote Tests inspired by {@link org.jabref.model.database.BibDatabaseContextTest#getFileDirectoriesWithRelativeMetadata}
+     * @implNote Tests inspired by {@link ~~(MemberReference type is missing or malformed)~~>org.jabref.model.database.BibDatabaseContextTest#getFileDirectoriesWithRelativeMetadata}
      */
```

There are also type issues in `build.gradle`, but I assume, they do not harm?

---

I made a check on my WSL (together with SDKMan). My results:

| Version | working |
| -- | -- |
| 21-tem | no |
| 21.0.1-tem | no |
| 21.0.3-tem | no |
| 21.0.4-tem | no |
| 21.0.5-tem | no |
| 22.0.1-tem | yes |

I do not know why it worked here with JDK21 in August.
